include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_private_types_in_public_api
    - use_key_in_widget_constructors
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - use_full_hex_values_for_flutter_colors

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    use_build_context_synchronously: ignore
